name: MSBuild

on:
- push
- pull_request

env:
  solution: Fronge.sln

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release, Distribute]
        platform: [x64, Win32]

    steps:
    - name: Clone repository to runner
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Build solution with Premake
      run: ${{ github.workspace }}\build.bat

    - name: Build program
      working-directory: ${{ github.workspace }}
      run: msbuild /m /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} ${{ env.solution }}